# Generated by Django 5.2.3 on 2025-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_formmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='size',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
